### PR TITLE
feat: page numbers

### PR DESCRIPTION
**Pull request by josemf**
# Why

Puppeteer (as every HTML to PDF tool out there) still lacks support for generated content. This usually comes as a surprise for most people that require some "advanced" features like creating table of contents (TOC) or being able to refer content by it's page number.

Alternative to puppeteer is wkhtmltopdf which does support TOC generation. However it fails to supply a HTML template API, so it's non customisable. Also does not support page number references within a pdf document. On top of that, the browser it uses is dated, which makes it difficult to user modern charting libraries and other advanced css and javascript features.

I needed those features for some client work, so ended up implementing it and port to this library. 

# How

It's simple to use:

```node
const browserless = require('browserless')

;(async () => {
  const url = 'https://example.com'
  const buffer = await browserless.pdf(url, { page_numbers: true })
  console.log(`PDF generated!`)
})()
```
On the HTML part use elements `<span class="pageNumber">` or `<span class="pageNumber" rel="someElementId">`. The resulting PDF will have both elements replaced by current page number or page number that corresponds to the referred `someElementId`.

## Full HTML Example

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <!-- <link rel="shortcut icon" href="" type="image/x-icon"> -->
        <title>Example</title>

        <style>
         section {page-break-after: always;}
        </style>        
    </head>
    <body>
        <section id="toc">
            <h1>Table of Contents:</h1>
            <ul>
                <li>Section 1 -- Page <span class="pageNumber" rel="section1">X</span></li>
                <li>Section 2 -- Page <a href="#section2" class="pageNumber" rel="section2">Y</a> with navigation</li>
                <li>Section 3 -- Page <span class="pageNumber" rel="section3"></span></li>
                <li>Section 4 -- Page <span class="pageNumber" rel="section4">Z</span></li>                
            </ul>
        </section>

        <section id="section1">
            <h1>Section 1</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>This should be page: <span class="pageNumber"></span></p>
        </section>

        <section id="section2">
            <h1>Section 2</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>This should be page: <span class="pageNumber"></span></p>
        </section>

        <section id="section3">
            <h1>Section 3</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>This should be page: <span class="pageNumber"></span></p>
            <p>And <b>Section 4</b> should be on page: <span class="pageNumber" rel="section4">PLACEHOLDER</span></p>
        </section>        

        <section id="section4">
            <h1>Section 4</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>This should be page: <span class="pageNumber"></span></p>
            <p>And <b>Section 2</b> should be on page: <span class="pageNumber" rel="section2"></span></p>            
        </section>
        
    </body>
</html>
```

# Implementation Details

I added some code to `browserless` in order to make extension features easier to implement. It could be more polished or allow some kind of dependency injection, making features pluggable.

Page numbers implementation uses [pdf-extract](https://github.com/nisaacson/pdf-extract), which have some dependencies that must be previously installed in the OS. OCR support is not required.

This implementation requires an extra PDF to be generated, so it will make the whole PDF processing and generation slower when using `page_numbers` option. This might have an impact for more processing intense production environments.

Thanks!

### CODE REVIEW

**Comment by Kikobeats** [comment]
First of all, this PR is GOLD. Thanks for that!

Until now, I tried to implement features in a pluggable way. 

For example, even you are not using `browserless`, you can connect your puppeteer code with `@browserless/goto` to have this kind of advantages.

Probably make sense create a new namespace called `@browserless/pdf` and put the current pdf implementation + this code there.

Then, you can delegate getting a pdf using `@browserless/pdf` and then, if you want to use page numbers, just pass the specific API parameter `pageNumbers` boolean to the module.

I think it fits better with the project structure, also causing less user friction (just install `@browserless/pdf` that contains all the pdf things necessary vs need to install to pdf + pdf dependiente module).

I can do it over your branch and then we can integrate it into the codebase. What do you think? 🙂

**Comment by josemf** [comment]
Hi Kiko 👋 

Thanks for following up. What you need from me in order to make the changes you suggest? Access to my repo only?

I like the way you architecture this library--it was one of the reason I picked this project. Also the project statement made sense.

If I may I would suggest other way to make the architecture pluggable. I guess the place we want to hook when developing an extension is around puppeteer `page.pdf(options)` or `page.screenshot(options)` code in the `browserless` module. The extension code might have some specific configuration, it will most likely evaluate some code on the browser and/or run some tool for before generating the actual output content. I would say a middleware pattern might be suited for this. Something that would be used like:

```node
const browserless = require('browserless')();
const adBlocker = require('@browserless/adblocker');
const pageNumbers = require('browserless-pagenumbers');
const extractHeaderAndFooter = require('browserless-extract-header-footer');

//...

browserless
  .pdf(url, 
          // Extensions are run in order they are declared here
          adBlocker({ additionalRules }), 
          pageNumbers(), 
          extractHeaderAndFooter({ onlyFooter: true }))
  .then(buffer => {
      // Do something
  });
```

Browserless middlewares could be implemented like this:

```node

module.exports = (config) => {
   // Might just check some dependencies, validates the config, etc
   // ...

  /**
    * @param options - Actual puppeteer options
    */
   return (page, options = {}) => {
     // page.evaluate(something)
     // etc
     // return Promise, or just return   
   }
}
```

This way extensions would manage their dependencies, documentation and testing. Also people would be able to collaborate/add extensions without having to fork and change browserless code.

Either way you're doing a good job maintaining the project,
Just let me know what you need from me in order to integrate this changes in the project.

👍

**Comment by Kikobeats** [comment]
Hey @josemf,

I think you're right, but maybe is too soon; feeling the library needs to get more traction in order to have a bigger plugin infrastructure.

In the middle time, I moved the original browserless PDF logic into a specific package ([@browserless/pdf](https://github.com/Kikobeats/browserless/tree/master/packages/pdf)), so we can use simple object flags to enable/disable specific things. Then, in the future, we can move there into specific packages.

One more thing. I noted your code added a temporal file logic because [pdf-extract](https://github.com/nisaacson/pdf-extract) needs it as input. Also, the lib need some specific globals.

Any reason why these things can't be done on memory?

Note that, although is not mandatory, browserless is oriented for serverless scenario, where you don't have guarantees for using temporal files or global programs.

**Comment by josemf** [comment]
Hi @Kikobeats 

That's fine 👍 

I'm curious to know how you plan to evolve this framework. I think there's a lot of convenience this framework could provide, like an option to extract <header> and <footer> tags and set header and footer templates in puppeteer.

Also it would be interesting to see what is possible to implement in terms of PDF metadata. PDF readers usually use those for author, keywords and table of contents.

---

I needed pdf-extract to achieve the simple task of matching text tokens to page numbers. I didn't spent a lot of time exploring pdf-extract API but it looks like it'll only work with a path to a PDF. I guess the main reason is that it depends on pdftk and pdftotext command line utilities, and those will work only with files.

Maybe [pdf2json](https://github.com/modesty/pdf2json/) would also do the trick.

**Comment by Kikobeats** [comment]
This PR is so outdated; I'm going to close this but I'm totally open to accept new additions like this under pdf package 🙂

**Pull request closed without merging**
