### PR TITLE
build: only use compatible rules

### PR DESCRIPTION
**Pull request by Kikobeats**
After using https://github.com/StevenBlack/hosts on production scenarios, I noted it makes the execution slow.

I'm not sure if this is happening based on the number of rules or because I'm doing an adaptation from the original rule definition.

### CODE REVIEW

**Comment by remusao** [comment]
Could you maybe paste the output of the conversion of the rules? It should not slow down execution.

**Comment by Kikobeats** [comment]
@remusao I think so, I prefer don't touch rules definition

**Comment by remusao** [comment]
> @remusao I think so, I prefer don't touch rules definition

Sounds good, I will add support for these rules back in the adblocker library so that you  can use them in the future.

**Comment by Kikobeats** [comment]
super awesome 🙂

**Pull request merged**
